### PR TITLE
added a list of users in the group API

### PR DESCRIPTION
**Pull request by hitohata**
## Overview of implementation

Added a list of users in the group API
#61 

## Review point

I added a new schema  `UsersBelongToGroup` referring to [the issue](https://github.com/genesis-tech-tribe/nishiki-documents/issues/61#issue-2022710695).
However, there is already a `User` schema. Should I use it as a return value instead of the new one?

### CODE REVIEW

**Review by taniguchiiqqq — CHANGES_REQUESTED** [review]
Thank you for updating. Now, I think it's better to define a response as a component, at least if the response has some data resource ( like user and container, group and container). Then we can assemble schema components in response components. But the thing is its bothersomeness. What do you think?

This is the code if we use response components.
FYI, I found the allOf keyword is really useful.
```yaml
  /users/{userId}:
      responses:
        '200':
          $ref: "#/components/responses/GetUserResponse"

  /groups/{groupId}/users:
      responses:
        "200":
          description: list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
~~~

 schemas:
    User:
      type: object
      properties:
        id:
          type: string
          nullable: false
          example: 1234567890
        name:
          type: string
          nullable: false
          example: John
    UserGroupRelation:
      type: object
      properties:
        groups:
          type: array
          nullable: false
          example:
            - groupId
          items:
            type: string
  responses:
    GetUserResponse:
      description: get user information.
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/User"
              - $ref: "#/components/schemas/UserGroupRelation"
```

**Comment by hitohata** [comment]
@taniguchiiqqq 
Thank you for reviewing. It seems that it's better to adapt the component and allOf.

However, I found that we need to get a consensus about the User component. I think we didn't have enough discussion about it. 
Should the groups in the User component be located here? I mean I think it seems better that the `/users/{userId}` returns the user ID and username, and we add a new API that is `/users/{userId}/groups` which returns a list of group IDs linked to the user.

**Comment by hitohata** [comment]
@taniguchiiqqq 
Oh, my example is not appropriate. 
The `/users/{userId}/groups`'s return value should be the Group component, I think. It will be more straightforward.
However, this approach will be a tradeoff between understandability and performance.

@kotaaaa 
What do you think from the point of the frontend?

**Comment by kotaaaa** [comment]
> 1, /groups/{groupId}/users include only user ids
2, /users/{userId}/groups include only group ids

1, We want not only user ids but user object (userId, userName) from this endpoint.
2, We want not only group ids but group object (groupId, groupName) from this endpoint.

**Pull request merged**
