### PR TITLE
Docs/50 add a db document

### PR DESCRIPTION
**Pull request by hitohata**
## Abstruct

Added a Dynamo DB definition document
Added a category table in the ER Diagram
Changed the folder and sidebar structure

### CODE REVIEW

**Review by taniguchiiqqq — COMMENTED** [review]
@hitohata 
Thank you for creating an elaborated document! I feel it need the access pattern "List of foods(/ certain category foods ) in all Groups which a User belongs to. ".
Honestly I'm not sure if my opinion makes sense. If not, I'm so sorry.

**Comment by hitohata** [comment]
@taniguchiiqqq 
Thank you for your review.
The list of food is contained in the container item as an attribute. May  I confirm your opinion, Do you think we need the "List of foods" or you just overlooked this attribute?

**Comment by hitohata** [comment]
@taniguchiiqqq 
By the way, I discarded the category.

**Comment by taniguchiiqqq** [comment]
@hitohata 
I think we need a "List of foods". I care about the access pattern when a user goes to the Food list page and then looks at all food across containers and groups, and also when they search food only by categories across groups and containers.
Is that case met by getting all groups and containers having food list that a user can access?
Or can we address that access pattern by getting the containers of all the groups to which the user belongs and all the Foods in them?

**Comment by hitohata** [comment]
@taniguchiiqqq 
I meant later. 
In this case, we assume that the user would want to check all foods that are related to the user. That requirement can be fulfilled by getting the list of containers.
The searching and filtering should be implemented in the font end.
Is my thinking correct?

**Review by taniguchiiqqq — APPROVED** [review]
Thank you! it answers my concern! Maybe I still think of DB as inappropriately RDB-like, so I'll adjust myself to DynamoDB through this project to contribute future changes.

**Pull request merged**
