### PR TITLE
Added category attributes to food entity

### PR DESCRIPTION
**Pull request by kotaaaa**
## Overview
- Added `category` attributes to food entity

## specification of category 
- `category` is string value
- number of `category` for each food is ~~0 or 1~~ 1

### CODE REVIEW

**Comment by hitohata** [comment]
Thank you!
The category looks needing to be implemented. So, I think this PR should merged. But would you mind if I ask one question?

> number of category for each food is 0 or 1

Does this mean that the category can be null?

@taniguchiiqqq 
Could you check and approve this PR? This is what you are implementing now.

**Comment by kotaaaa** [comment]
I overlooked there is one category called `Unselected`.
image

I guess number of category for each food should be 1.

@uskayyyyy 
Can you approve this specification?

**Review by taniguchiiqqq — APPROVED** [review]
Thank you so much! LGTM

**Comment by uskayyyyy** [comment]
@uskayyyyy 
It looks alright, but I thought "unselected" equals "null" before.
It is better to explicitly register a category as "unselected" for accessing data if it's possible.

**Review by uskayyyyy — APPROVED** [review]

**Comment by kota-kawaguchi** [comment]
Thank you all!!

**Comment by kotaaaa** [comment]
Thank you all!!

**Pull request merged**
